"""add kind to range

Revision ID: e401c89c53b1
Revises: f9502af35456
Create Date: 2026-09-14 23:21:07.274333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e401c89c53b1'
down_revision = 'f9502af35456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('range', schema=None) as batch_op:
        # server_default: le percentuali gia' inserite restano tali
        batch_op.add_column(sa.Column('kind', sa.String(length=10),
                                      nullable=False, server_default='pct'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('range', schema=None) as batch_op:
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
