"""add pace config to exercise catalog

Revision ID: f9502af35456
Revises: c28c2b280396
Create Date: 2026-09-13 16:54:02.393212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9502af35456'
down_revision = 'c28c2b280396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_distance', sa.Integer(), nullable=True))
        # server_default: la tabella ha gia' righe, senza un valore di riferimento
        # il vincolo NOT NULL le farebbe fallire
        batch_op.add_column(sa.Column('pct_mode', sa.String(length=20),
                                      nullable=False, server_default='literal'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_catalog', schema=None) as batch_op:
        batch_op.drop_column('pct_mode')
        batch_op.drop_column('ref_distance')

    # ### end Alembic commands ###
